// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyANRFBPATN3zlUwDxNzNCHftPydpdm5tk8',
    appId: '1:527722317012:web:152aa3128cb896e6e8a741',
    messagingSenderId: '527722317012',
    projectId: 'billion-beats',
    authDomain: 'billion-beats.firebaseapp.com',
    storageBucket: 'billion-beats.firebasestorage.app',
    measurementId: 'G-MH9BXLT9N5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBLJQ-bvGUpZjVYBfPBrtQpMxMqe4zD9L8',
    appId: '1:527722317012:android:f7e1889561d06eede8a741',
    messagingSenderId: '527722317012',
    projectId: 'billion-beats',
    storageBucket: 'billion-beats.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvamxlRFRRtNRl5WFkAsHZuhKjfvzAMBc',
    appId: '1:527722317012:ios:1c8bcaf9d5cd5a9fe8a741',
    messagingSenderId: '527722317012',
    projectId: 'billion-beats',
    storageBucket: 'billion-beats.firebasestorage.app',
    iosBundleId: 'com.example.tbbAdminPortal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvamxlRFRRtNRl5WFkAsHZuhKjfvzAMBc',
    appId: '1:527722317012:ios:1c8bcaf9d5cd5a9fe8a741',
    messagingSenderId: '527722317012',
    projectId: 'billion-beats',
    storageBucket: 'billion-beats.firebasestorage.app',
    iosBundleId: 'com.example.tbbAdminPortal',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyANRFBPATN3zlUwDxNzNCHftPydpdm5tk8',
    appId: '1:527722317012:web:84ca08457b778859e8a741',
    messagingSenderId: '527722317012',
    projectId: 'billion-beats',
    authDomain: 'billion-beats.firebaseapp.com',
    storageBucket: 'billion-beats.firebasestorage.app',
    measurementId: 'G-PMCFRZDRJK',
  );
}
